/**
 * What can be checked about prose, checked.
 *
 * The hand-written pages under `docs/` cannot be generated - they explain
 * decisions, not signatures - so they rot in the three ways prose always rots:
 * a link to a page that moved, a page nobody can reach from the navigation, and
 * a code example importing a symbol that has since been renamed.
 *
 * All three are mechanical, so all three are tests. What no test can check -
 * whether the paragraph is still true - is what review is for, and keeping the
 * mechanical failures out of the way is precisely what makes review about that.
 */

import { existsSync, readFileSync, readdirSync, statSync } from "node:fs";
import { dirname, join, relative, resolve } from "node:path";
import { publicNames } from "./api-docs.ts";

/** The documentation root, relative to the repository. */
export const DOCS_ROOT = "docs";

/** Pages generated by `npm run docs`: excluded from the prose checks. */
export const GENERATED_PREFIX = "docs/api/";

/** Every `.md` under `docs/`, repository-relative, in a stable order. */
export function docPages(root: string): string[] {
	const found: string[] = [];
	const walk = (dir: string) => {
		for (const entry of readdirSync(dir).sort()) {
			const path = join(dir, entry);
			if (statSync(path).isDirectory()) walk(path);
			else if (path.endsWith(".md")) found.push(relative(root, path));
		}
	};
	walk(join(root, DOCS_ROOT));
	return found;
}

/** The pages written by hand - the ones these checks apply to. */
export const handWritten = (pages: string[]): string[] => pages.filter((page) => !page.startsWith(GENERATED_PREFIX));

const LINK = /\[[^\]]*\]\(([^)\s]+)\)/g;

/**
 * Relative links that point at nothing, as `page -> target`.
 *
 * Anchors and external URLs are left alone: one is a question about a heading,
 * the other about a network, and neither belongs in an offline suite.
 */
export function brokenLinks(root: string, pages: string[]): string[] {
	const broken: string[] = [];
	for (const page of pages) {
		const text = readFileSync(join(root, page), "utf8");
		for (const [, target] of text.matchAll(LINK)) {
			if (!target || /^(https?:|mailto:|#)/.test(target)) continue;
			const path = resolve(join(root, dirname(page)), target.split("#")[0] as string);
			if (!existsSync(path)) broken.push(`${page} -> ${target}`);
		}
	}
	return broken;
}

/** Every `path` listed in `docs.json`, in navigation order. */
export function navigationPaths(root: string): string[] {
	const file = JSON.parse(readFileSync(join(root, DOCS_ROOT, "docs.json"), "utf8")) as {
		navigation: { items: { path: string }[] }[];
	};
	return file.navigation.flatMap((section) => section.items.map((item) => join(DOCS_ROOT, item.path)));
}

/**
 * Symbols imported from `pi-subagent` in a code fence that the library does not
 * export.
 *
 * This is the check that earns its keep: an example calling a renamed function
 * looks perfectly plausible to a reader, and is the one kind of documentation
 * error that wastes an hour.
 */
export function unknownImports(root: string, pages: string[]): string[] {
	const known = new Set(publicNames(join(root, "src/index.ts")));
	const unknown: string[] = [];

	for (const page of pages) {
		const text = readFileSync(join(root, page), "utf8");
		for (const [, names] of text.matchAll(/import\s*\{([^}]*)\}\s*from\s*"pi-subagent"/g)) {
			for (const raw of (names as string).split(",")) {
				const name = raw.replace(/^\s*type\s+/, "").trim();
				if (name && !known.has(name)) unknown.push(`${page}: ${name}`);
			}
		}
	}
	return unknown;
}
