/**
 * The shipped flows, drawn: `docs/reference/flows/`, one page per flow in the
 * package's `flows/`, each holding its Mermaid `flowchart`.
 *
 * Drawn from the checked flow, like the API reference is read from the
 * source, so a diagram cannot drift from its file: `test/docs.test.ts`
 * compares what this produces with what is committed. A shipped flow that
 * does not check has no page to draw, and throws.
 */

import { join, relative } from "node:path";
import { readAgentFile, type Agent } from "../src/agent.ts";
import { checkFlow, mermaidOf, type FlowCatalogue } from "../src/flow/index.ts";
import { readMarkdownDir } from "../src/markdown.ts";
import { blobUrl } from "./api-docs.ts";

/** Where the drawn flows live. Anything else under it is not ours to keep. */
export const FLOWS_DOCS_DIR = "docs/reference/flows";

const GENERATED = "<!-- Generated by scripts/gen-docs.ts from flows/. Do not edit by hand. -->";

/**
 * The flows and agents the package ships, and nothing of the user's or the
 * repository's `.pi/`: a page must read the same on every machine. Flow files
 * are named from the repository root for the same reason.
 */
export function shippedCatalogue(root: string): FlowCatalogue {
	const flows = readMarkdownDir(join(root, "flows")).map((file) => ({ ...file, filePath: relative(root, file.filePath) }));
	const agents = readMarkdownDir(join(root, "agents")).map((file) => readAgentFile(file, "builtin"));
	return { flows, agents: agents.filter((agent): agent is Agent => !("error" in agent)), brokenAgents: agents.filter((agent) => "error" in agent), cwd: root };
}

/** The whole of `docs/reference/flows/` for the flows of `catalogue`, as paths mapped to contents. */
export function generateFlowDocs(catalogue: FlowCatalogue, source: string): Map<string, string> {
	const files = new Map<string, string>();
	// By name, not by file: `build.md` sorts after `build-attended.md`.
	const names = catalogue.flows.map((file) => file.name).sort();
	files.set(join(FLOWS_DOCS_DIR, "index.md"), renderFlowIndex(names));
	for (const name of names) files.set(join(FLOWS_DOCS_DIR, `${name}.md`), renderFlow(catalogue, name, source));
	return files;
}

function renderFlow(catalogue: FlowCatalogue, name: string, source: string): string {
	const checked = checkFlow(name, catalogue);
	if (!checked.ok) throw new Error(`the shipped flow \`${name}\` does not check: ${checked.faults.map((fault) => `${fault.at}: ${fault.message}`).join("; ")}`);
	const { file, description } = checked.flow;
	return [GENERATED, "", `# \`${name}\``, "", description, "", `Source: [\`${file}\`](${source}/${file})`, "", "```mermaid", mermaidOf(checked.flow), "```", ""].join("\n");
}

function renderFlowIndex(names: readonly string[]): string {
	const lines = [GENERATED, "", "# Flows", "", "Each flow the package ships, drawn from its file by `mermaidOf`. How to read and write one is in", "[the guide](../../guide/flows.md).", ""];
	if (names.length === 0) return [...lines, "No flow ships yet.", ""].join("\n");
	return [...lines, ...names.map((name) => `- [\`${name}\`](${name}.md)`), "", "```{toctree}", ":hidden:", "", ...names, "```", ""].join("\n");
}

/** {@link generateFlowDocs} for the package at `root`. */
export function generateShippedFlowDocs(root: string): Map<string, string> {
	return generateFlowDocs(shippedCatalogue(root), blobUrl(root));
}
