"""Write the two combo lockups: the mark, and the word outlined from the vendored font.

    uv run --with fonttools python tools/build-lockup.py

The wordmark ships as outlines, not as live text, so it needs no font at display time. The
font is vendored under tools/fonts and its digest is checked before a glyph is read; it is
under the SIL Open Font License, which permits outlining glyphs into a derivative work.

Asset generator: it is run by hand, `npm test` does not run it, and nothing the library ships
depends on Python. Edit the figures here, never the path data in the SVG files.
"""

from __future__ import annotations

import hashlib
from pathlib import Path

from fontTools.pens.svgPathPen import SVGPathPen
from fontTools.pens.transformPen import TransformPen
from fontTools.ttLib import TTFont

HERE = Path(__file__).resolve().parent
FONT = HERE / "fonts" / "JetBrainsMono-Regular.ttf"
# JetBrains Mono 2.304, unmodified. See tools/fonts/README.md.
FONT_SHA256 = "a0bf60ef0f83c5ed4d7a75d45838548b1f6873372dfac88f71804491898d138f"

WORD = "combo"
SIZE = 25.0  # px
TRACKING = 0.5  # px between glyphs

# The mark's placement in the 64px box, and the extent of its artwork inside that box. Every
# other offset is derived from these.
MARK_SCALE = 0.8
MARK_DX, MARK_DY = 2.0, 6.0
MARK_X0, MARK_Y0, MARK_X1, MARK_Y1 = 8.0, 12.0, 56.0, 52.0

GAP_EM = 0.5  # space between mark and word, as a fraction of the type size

OUT = HERE.parent / "docs" / "_static" / "logo"

# One palette per ground.
THEMES = {
	"light": {"bars": "#232B33", "bracket": "#A97C2A", "ink": "#232B33"},
	"dark": {"bars": "#C9D3DB", "bracket": "#C79338", "ink": "#C9D3DB"},
}

TEMPLATE = """<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 {width} 64" \
width="{width}" height="64" role="img" aria-label="combo">
  <title>combo</title>
  <!-- Horizontal lockup, {theme} ground. Generated by tools/build-lockup.py from {font}
       at {size}px with {tracking}px tracking - edit the script, not the path data. -->
  <g transform="translate({mark_dx} {mark_dy}) scale({mark_scale})">
    <g fill="{bars}">
      <rect x="27" y="16" width="29" height="6" />
      <rect x="27" y="29" width="29" height="6" />
      <rect x="27" y="42" width="29" height="6" />
    </g>
    <path fill="{bracket}" d="M8 12 H22 V18 H14 V46 H22 V52 H8 Z" />
  </g>
  <path fill="{ink}" transform="translate({text_x} {baseline}) scale({scale} -{scale})"
        d="{word}" />
</svg>
"""


def outline(word: str, font: TTFont) -> tuple[str, float]:
	"""Return the word as one path in font units, and its advance in font units."""
	upem = font["head"].unitsPerEm
	glyph_set = font.getGlyphSet()
	cmap = font.getBestCmap()
	widths = font["hmtx"]
	tracking_units = TRACKING * upem / SIZE

	parts: list[str] = []
	x = 0.0
	for char in word:
		name = cmap[ord(char)]
		pen = SVGPathPen(glyph_set)
		glyph_set[name].draw(TransformPen(pen, (1, 0, 0, 1, x, 0)))
		commands = pen.getCommands()
		if commands:
			parts.append(commands)
		x += widths[name][0] + tracking_units

	return " ".join(parts), x - tracking_units


def main() -> None:
	if not FONT.exists():
		raise SystemExit(f"font not found: {FONT}")

	digest = hashlib.sha256(FONT.read_bytes()).hexdigest()
	if digest != FONT_SHA256:
		raise SystemExit(
			f"{FONT.name} is not the font this lockup was drawn with.\n"
			f"  expected {FONT_SHA256}\n"
			f"  found    {digest}\n"
			"Restore it, or update FONT_SHA256 and tools/fonts/README.md."
		)

	font = TTFont(FONT)
	upem = font["head"].unitsPerEm
	scale = SIZE / upem
	path, advance_units = outline(WORD, font)

	# The word is all lower case: the mark is centred on the x-height band, not on the em box.
	x_height = font["OS/2"].sxHeight * scale
	mark_left = MARK_DX + MARK_X0 * MARK_SCALE
	mark_right = MARK_DX + MARK_X1 * MARK_SCALE
	mark_centre_y = MARK_DY + (MARK_Y0 + MARK_Y1) / 2 * MARK_SCALE

	text_x = mark_right + GAP_EM * SIZE
	baseline = mark_centre_y + x_height / 2
	width = round(text_x + advance_units * scale + mark_left)
	print(f"x-height {x_height:.2f}px  baseline {baseline:.2f}  word starts {text_x:.2f}")

	for theme, colours in THEMES.items():
		svg = TEMPLATE.format(
			width=width,
			theme=theme,
			font=FONT.name,
			size=SIZE,
			tracking=TRACKING,
			text_x=f"{text_x:.4g}",
			baseline=f"{baseline:.4g}",
			scale=f"{scale:.6g}",
			mark_dx=f"{MARK_DX:.4g}",
			mark_dy=f"{MARK_DY:.4g}",
			mark_scale=f"{MARK_SCALE:.4g}",
			word=path,
			**colours,
		)
		target = OUT / f"combo-lockup-{theme}.svg"
		target.write_text(svg, encoding="utf-8")
		print(f"docs/_static/logo/{target.name}  {width}x64")


if __name__ == "__main__":
	main()
